"""create registration table

Revision ID: 6fb0f5b3ea17
Revises: 
Create Date: 2025-02-11 11:22:34.897519

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6fb0f5b3ea17'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('registration',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('persons', sa.Text(), nullable=False),
    sa.Column('contact_firstname', sa.String(length=50), nullable=False),
    sa.Column('contact_lastname', sa.String(length=50), nullable=False),
    sa.Column('phone_number', sa.String(length=15), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('confirmed', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('registration', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_registration_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_registration_email'), ['email'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('registration', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_registration_email'))
        batch_op.drop_index(batch_op.f('ix_registration_created_at'))

    op.drop_table('registration')
    # ### end Alembic commands ###
